### ISSUE TITLE
Hunchback issue on Mixamo rig avatar

### ISSUE THREAD

**Issue by segunabiodun** [umasteeringgroup/content-pack#3]
**Description**
The Mixamo Rig Male has a hunchback in some poses while playing some Mixamo animations. This issue was observed in both Mixamo and Unity.

**Environment:**
 - mixamo.com
 - Unity Version: 2019.4.14f1

**To Reproduce**
1. Go to mixamo.com
2. Import UMA Male Mixamo Rig.fbx
3. Load the animation Breakdance Uprock To Ground
4. Watch the animation play, you'll notice that the avatar has a hunchback in some parts of the animation. The hunchback appears in both Mixamo and Unity. Please see attached screenshot.
<img width="1193" alt="UMA Mixamo hunchback" src="https://user-images.githubusercontent.com/19616990/105221332-4010ec80-5b59-11eb-9f18-4bb5516c9ae9.png">

**Comment by Jaimi** [comment]
When you import mixamo animations into Unity, you need to first import the Mixamo animation with the T-Pose, and generate the avatar from that model. Then in your animation, use the avatar from the T-Pose asset.
