### ISSUE TITLE
Blender does not detect a module to install

### ISSUE THREAD

**Issue by narutouzemaki802** [umasteeringgroup/content-pack#4]
I download the zip, attempt to install the UMA Content in blender, it says () Modules have been installed and it seems there has been no new add on installed at all. Do not really know how to go about fixing this it, is the first time this has happened with any blender add on to this point.

**Comment by Jaimi** [comment]
Most likely you are trying to load the UI from the blender file. Please turn that off in preferences, or on the open dialog (the gear icon on the top)

**Comment by narutouzemaki802** [comment]
I have turned loading the UI off and have attempted several combinations of the load settings with no luck. I have tried to re-install blender as well as the zip a couple times. It just will not load the module it keeps saying () modules have been added out of the correct name of the file so I am still stumped, it appears loading everything from the zip is fine it it just how blender is trying to extract the module.

**Comment by narutouzemaki802** [comment]
update, for some reason when I install these files on blender they are stored as blend files in to my support library but still no module or add-on. Every UMA file in the code is on separate blend files so I am not sure quite how to fix this but I am sure It has to be through blender.

**Comment by Jaimi** [comment]
There isn't an add-on. This is just the blend files for the UMA content.
